// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbrNR75-DIBegR6iBSVHPNICpjAV9mzgk',
    appId: '1:1034299480827:web:8b2bc22f7f1dfff5606e5e',
    messagingSenderId: '1034299480827',
    projectId: 'skid-app-499',
    authDomain: 'skid-app-499.firebaseapp.com',
    storageBucket: 'skid-app-499.appspot.com',
    measurementId: 'G-YKZBXGCY8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4UA33To-V66Gq87LFjImEAa1YrbhiosM',
    appId: '1:1034299480827:android:ebaa1249fcb1dab7606e5e',
    messagingSenderId: '1034299480827',
    projectId: 'skid-app-499',
    storageBucket: 'skid-app-499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0sCtfLwLAL7ZGtgjPGangmOy3pfIWUdQ',
    appId: '1:1034299480827:ios:1f98f753819db0b3606e5e',
    messagingSenderId: '1034299480827',
    projectId: 'skid-app-499',
    storageBucket: 'skid-app-499.appspot.com',
    iosClientId: '1034299480827-vuan6njk7kjh0d8i71o5cvas6itu633q.apps.googleusercontent.com',
    iosBundleId: 'com.example.skid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0sCtfLwLAL7ZGtgjPGangmOy3pfIWUdQ',
    appId: '1:1034299480827:ios:1f98f753819db0b3606e5e',
    messagingSenderId: '1034299480827',
    projectId: 'skid-app-499',
    storageBucket: 'skid-app-499.appspot.com',
    iosClientId: '1034299480827-vuan6njk7kjh0d8i71o5cvas6itu633q.apps.googleusercontent.com',
    iosBundleId: 'com.example.skid',
  );
}
